// Generated from the live SQLite schema (sqlite3 invoices.db .schema).
// Regenerate with scripts/gen-schema.sh after any Python-side migration.
export const SCHEMA: string[] = [
  "CREATE TABLE invoices (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                invoice_number INTEGER UNIQUE NOT NULL,\n                year INTEGER NOT NULL,\n                month INTEGER NOT NULL,\n                hours REAL NOT NULL,\n                rate REAL NOT NULL,\n                vat_rate REAL NOT NULL,\n                subtotal REAL NOT NULL,\n                tax REAL NOT NULL,\n                total REAL NOT NULL,\n                issued_date TEXT NOT NULL,\n                due_date TEXT NOT NULL,\n                notes TEXT DEFAULT '',\n                paid_status TEXT NOT NULL DEFAULT 'unpaid',\n                paid_date TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE expenses (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                expense_date TEXT NOT NULL,\n                description TEXT NOT NULL,\n                amount REAL NOT NULL,\n                category TEXT NOT NULL,\n                original_amount REAL,\n                original_currency TEXT,\n                scan_file TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            , trip_id INTEGER REFERENCES trips(id))",
  "CREATE TABLE expense_reports (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                report_number INTEGER NOT NULL,\n                year INTEGER NOT NULL,\n                total REAL NOT NULL,\n                expense_count INTEGER NOT NULL,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            , month INTEGER, reimbursed_at TEXT)",
  "CREATE TABLE customers (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                name TEXT NOT NULL,\n                address TEXT,\n                city TEXT,\n                country TEXT,\n                email TEXT,\n                reference TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE obligations (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                obligation_type TEXT NOT NULL,\n                period_label TEXT NOT NULL,\n                period_year INTEGER NOT NULL,\n                amount REAL NOT NULL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                due_date TEXT,\n                status TEXT NOT NULL DEFAULT 'unpaid',\n                notes TEXT,\n                doc_file TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            , recurrence TEXT DEFAULT 'none', parent_obligation_id INTEGER, expected_bill_date TEXT, expected_bill_amount REAL)",
  "CREATE TABLE account_transfers (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                transfer_date TEXT NOT NULL,\n                direction TEXT NOT NULL,\n                amount REAL NOT NULL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                description TEXT,\n                doc_file TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE income_entries (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                income_date TEXT NOT NULL,\n                source TEXT NOT NULL,\n                description TEXT,\n                amount REAL NOT NULL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                category TEXT NOT NULL DEFAULT 'Other',\n                doc_file TEXT,\n                invoice_id INTEGER,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE UNIQUE INDEX idx_income_entries_invoice ON income_entries(invoice_id) WHERE invoice_id IS NOT NULL",
  "CREATE TABLE cash_balance (\n                id INTEGER PRIMARY KEY CHECK (id = 1),\n                balance REAL NOT NULL DEFAULT 0,\n                as_of TEXT NOT NULL DEFAULT (date('now')),\n                notes TEXT DEFAULT '',\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE payroll_settings (\n                id INTEGER PRIMARY KEY CHECK (id = 1),\n                employer_name TEXT NOT NULL,\n                employee_name TEXT NOT NULL,\n                employee_address TEXT,\n                employment_start TEXT NOT NULL,\n                canton TEXT NOT NULL DEFAULT 'Zurich',\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                payment_day INTEGER NOT NULL DEFAULT 25,\n                gross_monthly REAL NOT NULL,\n                ahv_employee_pct REAL NOT NULL,\n                ahv_employer_pct REAL NOT NULL,\n                alv_employee_pct REAL NOT NULL,\n                alv_employer_pct REAL NOT NULL,\n                bvg_monthly_employee REAL NOT NULL,\n                bvg_monthly_employer REAL NOT NULL,\n                bvg_provider TEXT,\n                uvg_employee_monthly REAL NOT NULL,\n                uvg_employer_monthly REAL NOT NULL,\n                ktg_monthly_total REAL NOT NULL,\n                ktg_employer_share_pct REAL NOT NULL DEFAULT 70,\n                fak_employer_pct REAL NOT NULL DEFAULT 1.2,\n                source_tax_monthly REAL NOT NULL DEFAULT 0,\n                source_tax_tariff TEXT DEFAULT '',\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            , sai_employee_monthly REAL NOT NULL DEFAULT 0, sai_employer_share_pct REAL NOT NULL DEFAULT 50)",
  "CREATE TABLE payslips (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                year INTEGER NOT NULL,\n                month INTEGER NOT NULL,\n                issued_date TEXT NOT NULL,\n                payment_date TEXT NOT NULL,\n                gross REAL NOT NULL,\n                emp_ahv REAL NOT NULL,\n                emp_alv REAL NOT NULL,\n                emp_bvg REAL NOT NULL,\n                emp_uvg REAL NOT NULL,\n                emp_ktg REAL NOT NULL,\n                emp_source_tax REAL NOT NULL DEFAULT 0,\n                emp_total_deductions REAL NOT NULL,\n                net_salary REAL NOT NULL,\n                employer_ahv REAL NOT NULL,\n                employer_alv REAL NOT NULL,\n                employer_bvg REAL NOT NULL,\n                employer_uvg REAL NOT NULL,\n                employer_ktg REAL NOT NULL,\n                employer_fak REAL NOT NULL DEFAULT 0,\n                employer_total REAL NOT NULL,\n                total_employer_cost REAL NOT NULL,\n                status TEXT NOT NULL DEFAULT 'issued',\n                pdf_file TEXT,\n                notes TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')), source TEXT NOT NULL DEFAULT 'generated',\n                UNIQUE(year, month)\n            )",
  "CREATE TABLE budget_items (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                grp TEXT NOT NULL,\n                subcategory TEXT NOT NULL,\n                budgeted REAL NOT NULL DEFAULT 0,\n                balance REAL NOT NULL DEFAULT 0,\n                last_contributed_month TEXT,\n                sort_order INTEGER NOT NULL DEFAULT 0\n            )",
  "CREATE TABLE budget_ledger (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                budget_item_id INTEGER NOT NULL,\n                entry_date TEXT NOT NULL,\n                amount REAL NOT NULL,\n                description TEXT,\n                kind TEXT NOT NULL,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                FOREIGN KEY (budget_item_id) REFERENCES budget_items(id)\n            )",
  "CREATE UNIQUE INDEX idx_budget_items_grp_sub ON budget_items(grp, subcategory)",
  "CREATE TABLE user_preferences (\n                id INTEGER PRIMARY KEY,\n                prefs TEXT NOT NULL DEFAULT '{}',\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE shared_links (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                token TEXT UNIQUE NOT NULL,\n                section TEXT NOT NULL,\n                year INTEGER NOT NULL,\n                label TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE company_docs (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                doc_date TEXT NOT NULL,\n                vendor TEXT NOT NULL,\n                description TEXT NOT NULL,\n                amount REAL NOT NULL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                category TEXT NOT NULL,\n                due_date TEXT,\n                status TEXT NOT NULL DEFAULT 'unpaid',\n                doc_file TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            , recurrence TEXT DEFAULT 'none', parent_doc_id INTEGER, vat_amount REAL DEFAULT 0, vat_rate REAL DEFAULT 0, paid_via TEXT NOT NULL DEFAULT 'company', reimbursed_at TEXT, doc_url TEXT, original_amount REAL, original_currency TEXT, fx_rate REAL)",
  "CREATE TABLE reserves (\n                id INTEGER PRIMARY KEY,\n                name TEXT NOT NULL UNIQUE,\n                purpose TEXT,\n                target_amount REAL NOT NULL,\n                target_date TEXT,\n                monthly_accrual REAL NOT NULL DEFAULT 0,\n                accrual_start TEXT,\n                accumulated_manual REAL NOT NULL DEFAULT 0,\n                is_active INTEGER NOT NULL DEFAULT 1,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE trips (\n                id INTEGER PRIMARY KEY,\n                name TEXT NOT NULL,\n                purpose TEXT,\n                start_date TEXT NOT NULL,\n                end_date TEXT NOT NULL,\n                countries TEXT,\n                notes TEXT,\n                is_active INTEGER NOT NULL DEFAULT 1,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE bank_statements (\n                id INTEGER PRIMARY KEY,\n                bank TEXT NOT NULL DEFAULT 'UBS',\n                account_label TEXT,\n                iban TEXT,\n                period_start TEXT NOT NULL,\n                period_end TEXT NOT NULL,\n                statement_type TEXT NOT NULL DEFAULT 'monthly',\n                opening_balance REAL,\n                closing_balance REAL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                statement_file_pdf TEXT,\n                statement_file_xml TEXT,\n                notes TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE shareholder_loans (\n                id INTEGER PRIMARY KEY,\n                loan_date TEXT NOT NULL,\n                amount REAL NOT NULL,\n                currency TEXT NOT NULL DEFAULT 'CHF',\n                direction TEXT NOT NULL,\n                is_subordinated INTEGER NOT NULL DEFAULT 0,\n                notes TEXT,\n                document_file TEXT,\n                repayment_date TEXT,\n                is_repaid INTEGER NOT NULL DEFAULT 0,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE vehicles (\n                id INTEGER PRIMARY KEY,\n                name TEXT NOT NULL,\n                vendor TEXT,\n                purchase_date TEXT NOT NULL,\n                purchase_price REAL NOT NULL,\n                vat_paid REAL,\n                purchase_invoice_file TEXT,\n                registration_number TEXT,\n                fahrzeugausweis_file TEXT,\n                depreciation_method TEXT DEFAULT 'degressive_40',\n                privatanteil_method TEXT DEFAULT 'pauschal',\n                privatanteil_monthly REAL,\n                is_active INTEGER NOT NULL DEFAULT 1,\n                notes TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now')),\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE bank_transactions (\n                id INTEGER PRIMARY KEY,\n                statement_id INTEGER REFERENCES bank_statements(id),\n                trade_date TEXT NOT NULL,\n                booking_date TEXT,\n                value_date TEXT,\n                amount REAL NOT NULL,\n                balance_after REAL,\n                transaction_no TEXT,\n                description1 TEXT,\n                description2 TEXT,\n                description3 TEXT,\n                counterparty TEXT,\n                reference TEXT,\n                matched_invoice_id INTEGER REFERENCES invoices(id),\n                matched_bill_id INTEGER REFERENCES company_docs(id),\n                matched_obligation_id INTEGER REFERENCES obligations(id),\n                auto_categorized TEXT,\n                is_reviewed INTEGER NOT NULL DEFAULT 0,\n                notes TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE reserve_ledger (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                reserve_id INTEGER NOT NULL,\n                entry_date TEXT NOT NULL,\n                kind TEXT NOT NULL,              -- contribute | withdraw\n                amount REAL NOT NULL,\n                description TEXT,\n                created_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )",
  "CREATE TABLE vat_settings (\n                id INTEGER PRIMARY KEY CHECK (id = 1),\n                estimate_missing INTEGER NOT NULL DEFAULT 1,\n                estimate_rate REAL NOT NULL DEFAULT 8.1,\n                excluded_categories TEXT NOT NULL DEFAULT '[\"Insurance\",\"Bank Fees\",\"Payroll Settlement\",\"Taxes / VAT\"]',\n                flat_quarterly_deduction REAL NOT NULL DEFAULT 0,\n                updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n            )"
];

export const SINGLETON_SEEDS: string[] = [
  "INSERT INTO cash_balance (id, balance, as_of) SELECT 1, 0, date('now') WHERE NOT EXISTS (SELECT 1 FROM cash_balance WHERE id=1)",
  "INSERT INTO user_preferences (id, prefs) SELECT 1, '{}' WHERE NOT EXISTS (SELECT 1 FROM user_preferences WHERE id=1)",
  `INSERT INTO payroll_settings
    (id, employer_name, employee_name, employee_address, employment_start,
     canton, currency, payment_day, gross_monthly,
     ahv_employee_pct, ahv_employer_pct, alv_employee_pct, alv_employer_pct,
     bvg_monthly_employee, bvg_monthly_employer, bvg_provider,
     uvg_employee_monthly, uvg_employer_monthly, ktg_monthly_total, ktg_employer_share_pct)
   SELECT 1, 'Muster Consulting GmbH', 'Max Muster',
     'c/o Alpen Treuhand AG, Musterstrasse 1, 8000 Zurich',
     '2026-04-01', 'Zurich', 'CHF', 25, 13000.00, 5.3, 5.3, 1.1, 1.1,
     522.60, 783.90, 'AXA', 120.00, 150.00, 290.04, 70.0
   WHERE NOT EXISTS (SELECT 1 FROM payroll_settings WHERE id=1)`,
  `INSERT INTO customers (name, address, city, country, email, reference)
   SELECT 'Acme Technologies', 'Louis Giroud-Strasse 26/3.OG', '4600 Olten',
     'Switzerland', 'invoices@acme.example', '101119.LOD-SW_GCS-24032'
   WHERE NOT EXISTS (SELECT 1 FROM customers LIMIT 1)`,
];
